# Generated by Django 3.2.8 on 2022-04-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=7, editable=False, max_digits=15, null=True, verbose_name='Gebühren'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='totalValue',
            field=models.DecimalField(decimal_places=7, editable=False, max_digits=15, null=True, verbose_name='Gebühren'),
        ),
    ]
