# Generated by Django 4.0.4 on 2022-04-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220421_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='block',
            name='acceptedAt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='verifiziert am'),
        ),
        migrations.AddField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(editable=False, null=True, verbose_name='erstellt am'),
        ),
    ]
