# Generated by Django 4.0.4 on 2022-04-20 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Blocknummer')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am')),
                ('transactionsIncluded', models.TextField(editable=False, null=True, verbose_name='beinhaltete Transaktionen')),
                ('transactionsCount', models.PositiveIntegerField(editable=False, null=True, verbose_name='Anzahl der Transaktionen')),
                ('transactionsValueTotal', models.DecimalField(decimal_places=7, editable=False, max_digits=15, null=True, verbose_name='Gesamtvolumen')),
                ('miner', models.GenericIPAddressField(editable=False, null=True, verbose_name='Miner (IP)')),
                ('size', models.PositiveIntegerField(editable=False, null=True, verbose_name='Größe (Byte)')),
                ('nonce', models.PositiveBigIntegerField(editable=False, null=True, verbose_name='Nonce')),
                ('currHash', models.CharField(editable=False, max_length=128, null=True, verbose_name='Hash des Blocks')),
                ('prevHash', models.CharField(editable=False, max_length=128, null=True, verbose_name='Hash des Vorgängerblocks')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='Transaktions-Id')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='erstellt am')),
                ('sender', models.TextField(editable=False, null=True, verbose_name='Sender')),
                ('senderValue', models.TextField(editable=False, null=True, verbose_name='Sender-Betrag')),
                ('recipient', models.TextField(editable=False, null=True, verbose_name='Empfänger')),
                ('recipientValue', models.TextField(editable=False, null=True, verbose_name='Empfänger-Betrag')),
                ('blockContained', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.block', verbose_name='enthalten in Block')),
            ],
        ),
    ]
