# Generated by Django 4.0.4 on 2022-05-08 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_block_createdat_block_acceptedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('Todo', 'To be done'), ('Fini', 'Finished')], default='Todo', max_length=4)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lowerBound', models.IntegerField()),
                ('upperBound', models.IntegerField()),
            ],
        ),
    ]
